name: Release General

on:
  push:
    tags:
      - '[0-9]*.*'

jobs:
  build:
    name: Build and upload release artifacts
    needs: create
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout tree ...
        uses: actions/checkout@v2
      - name: Check build ...
        run: make
      - name: Build release ...
        run: |
          make release
          mkdir -p artifacts/
          cp ../*.tar.* ../*.md5 ../*.sha* artifacts/
      - name: Upload release artifacts ...
        uses: skx/github-action-publish-binaries@release-0.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create.outputs.release_id }}
          args: artifacts/*
